### ISSUE TITLE
After some time integers becomes larger

### ISSUE THREAD

**Issue by shapkarin** [scanf/xiyo.imba#4]
I guess letters can brings larger namespace with less symbols.

**Comment by aalemayhu** [comment]
I have actually started rewriting it locally and have some changes in mind to fix that and related issues. Will keep this open until I push my local changes.

Thanks.

**Comment by aalemayhu** [comment]
Unfortunately I won’t be able to follow up this project due to time constraint.
Hence I am archiving it. Thank you for taking the time to open this issue.
